# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: app-deployment
#   labels:
#     app: webapp
# spec:
#   replicas: 2
#   selector:
#     matchLabels:
#       app: webapp
#   template:
#     metadata:
#       labels:
#         app: webapp
#     spec:
#       containers:
#       - name: webapp
#         image: shaizah/kube:web-kube
#         ports:
#         - containerPort: 80
#         env:
#         - name: BACKEND_URL
#           value: "/api"



apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: server
        image: shaizah/kube:web-kube-v2
        ports:
        - containerPort: 80
        env:
        - name: BACKEND_URL
          value: "http://localhost:30081"