apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9zaGFpemFobGFiaXF1ZTpNb29zaHkxMi4zNEBjbHVzdGVyMC5kOWZ6aHAzLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw
  JWT_SECRET: dzh5TlJ5bHhXSkFzSzJTeElacEoxU1FLRHhHRnh0d2hJUGRtWGNkTHFKUA==
stringData:
  CLIENT_IP: "http://localhost:80"
  



